# Generated by Django 4.1.7 on 2023-03-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_gbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images'),
        ),
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='players_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='players_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
